# Generated by Django 6.1.1 on 2026-09-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manudux", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidestep",
            options={
                "ordering": ["step_number"],
                "verbose_name": "Guide step",
                "verbose_name_plural": "Guide steps",
            },
        ),
    ]
