# Generated by Django 6.1.1 on 2026-09-10 18:52

import manudux.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manudux", "0002_alter_guidestep_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidefile",
            name="file",
            field=models.FileField(
                upload_to="guides/files/",
                validators=[
                    manudux.validators.FileExtensionAndSizeValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "svg",
                            "mp4",
                            "zip",
                        ],
                        max_size_mb=25,
                    )
                ],
            ),
        ),
    ]
