# Generated by Django 6.1.1 on 2026-09-10 22:00

import django.db.models.deletion
import manudux.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manudux", "0004_appliance_maintenancetask_maintenancelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="estimated_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="insurance_company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="insurance_expires",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="lot_size_sqm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="parcel_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="size_sqm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="year_built",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("deed", "Deed"),
                            ("insurance", "Insurance"),
                            ("inspection", "Inspection report"),
                            ("floor_plan", "Floor plan"),
                            ("tax", "Tax"),
                            ("warranty", "Warranty"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="properties/documents/",
                        validators=[
                            manudux.validators.FileExtensionAndSizeValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ],
                                max_size_mb=25,
                            )
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="manudux.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property document",
                "verbose_name_plural": "Property documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
