# Generated by Django 6.1.1 on 2026-09-11 17:59

import django.db.models.deletion
import manudux.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manudux", "0006_locationtype_location_location_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplianceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Appliance Type",
                "verbose_name_plural": "Appliance Types",
            },
        ),
        migrations.CreateModel(
            name="ApplianceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("warranty", "Warranty"),
                            ("manual", "Manual"),
                            ("inspection", "Inspection report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="appliances/documents/",
                        validators=[
                            manudux.validators.FileExtensionAndSizeValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ],
                                max_size_mb=25,
                            )
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="manudux.appliance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appliance document",
                "verbose_name_plural": "Appliance documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="appliance",
            name="appliance_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appliances",
                to="manudux.appliancetype",
            ),
        ),
    ]
