# Generated by Django 6.1.1 on 2026-09-11 18:33

import manudux.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manudux", "0007_appliancetype_appliancedocument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="maintenance/receipts/",
                validators=[
                    manudux.validators.FileExtensionAndSizeValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xlsx",
                            "jpg",
                            "jpeg",
                            "png",
                        ],
                        max_size_mb=25,
                    )
                ],
            ),
        ),
    ]
