# Generated by Django 6.1.1 on 2026-09-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manudux", "0008_maintenancelog_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appliance",
            name="guest_visible",
            field=models.BooleanField(
                default=False,
                help_text="Show this appliance to anyone browsing with a guest code.",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="guest_visible",
            field=models.BooleanField(
                default=False,
                help_text="Show this location to anyone browsing with a guest code.",
            ),
        ),
        migrations.CreateModel(
            name="GuestCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Who this code was given to, e.g. a tenant's name.",
                        max_length=255,
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_codes",
                        to="manudux.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest code",
                "verbose_name_plural": "Guest codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
