# Generated by Django 6.1.1 on 2026-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manudux", "0009_appliance_guest_visible_location_guest_visible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="guest_visible",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Show this guide's steps to anyone browsing with a guest "
                    "code, when it's linked from a guest-visible property, "
                    "location, or appliance."
                ),
            ),
        ),
    ]
