version: "3"

services:
    web:
        build: .
        volumes:
            - .:/var/manudux
            - manudux_data:/var/manudux/data
            - manudux_media:/var/manudux/media
        ports:
            - "8000:8000"
        env_file:
            - .env
        networks:
            - backend

volumes:
    manudux_data:
    manudux_media:

networks:
    backend:
